server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_HOST:eureka-server.prod.internal}
    prefer-ip-address: true

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-server.prod.internal}:${SERVER_PORT:8761}/eureka/

  server:
    enable-self-preservation: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
